apiVersion: apiextensions.k8s.io/v1 # Hack because controller-gen complains if we don't have this
name: "[TechPreview] DNS"
crd: 0000_10_config-operator_01_dns-TechPreviewNoUpgrade.crd.yaml
tests:
  onCreate:
  onUpdate:
